using System.Collections.Generic;

namespace Plugin.Iconize.Fonts
{
    /// <summary>
    /// Defines the <see cref="SimpleLineIconsCollection" /> icon collection.
    /// </summary>
    public static class SimpleLineIconsCollection
    {
        /// <summary>
        /// Gets the icons.
        /// </summary>
        /// <value>The icons.</value>
        public static IList<IIcon> Icons { get; } = new List<IIcon>();

        /// <summary>
        /// Initializes the <see cref="SimpleLineIconsCollection" /> class.
        /// </summary>
        static SimpleLineIconsCollection()
        {
            Icons.Add("icon-user", '\ue005');
            Icons.Add("icon-people", '\ue001');
            Icons.Add("icon-user-female", '\ue000');
            Icons.Add("icon-user-follow", '\ue002');
            Icons.Add("icon-user-following", '\ue003');
            Icons.Add("icon-user-unfollow", '\ue004');
            Icons.Add("icon-login", '\ue066');
            Icons.Add("icon-logout", '\ue065');
            Icons.Add("icon-emotsmile", '\ue021');
            Icons.Add("icon-phone", '\ue600');
            Icons.Add("icon-call-end", '\ue048');
            Icons.Add("icon-call-in", '\ue047');
            Icons.Add("icon-call-out", '\ue046');
            Icons.Add("icon-map", '\ue033');
            Icons.Add("icon-location-pin", '\ue096');
            Icons.Add("icon-direction", '\ue042');
            Icons.Add("icon-directions", '\ue041');
            Icons.Add("icon-compass", '\ue045');
            Icons.Add("icon-layers", '\ue034');
            Icons.Add("icon-menu", '\ue601');
            Icons.Add("icon-list", '\ue067');
            Icons.Add("icon-options-vertical", '\ue602');
            Icons.Add("icon-options", '\ue603');
            Icons.Add("icon-arrow-down", '\ue604');
            Icons.Add("icon-arrow-left", '\ue605');
            Icons.Add("icon-arrow-right", '\ue606');
            Icons.Add("icon-arrow-up", '\ue607');
            Icons.Add("icon-arrow-up-circle", '\ue078');
            Icons.Add("icon-arrow-left-circle", '\ue07a');
            Icons.Add("icon-arrow-right-circle", '\ue079');
            Icons.Add("icon-arrow-down-circle", '\ue07b');
            Icons.Add("icon-check", '\ue080');
            Icons.Add("icon-clock", '\ue081');
            Icons.Add("icon-plus", '\ue095');
            Icons.Add("icon-minus", '\ue615');
            Icons.Add("icon-close", '\ue082');
            Icons.Add("icon-event", '\ue619');
            Icons.Add("icon-exclamation", '\ue617');
            Icons.Add("icon-organization", '\ue616');
            Icons.Add("icon-trophy", '\ue006');
            Icons.Add("icon-screen-smartphone", '\ue010');
            Icons.Add("icon-screen-desktop", '\ue011');
            Icons.Add("icon-plane", '\ue012');
            Icons.Add("icon-notebook", '\ue013');
            Icons.Add("icon-mustache", '\ue014');
            Icons.Add("icon-mouse", '\ue015');
            Icons.Add("icon-magnet", '\ue016');
            Icons.Add("icon-energy", '\ue020');
            Icons.Add("icon-disc", '\ue022');
            Icons.Add("icon-cursor", '\ue06e');
            Icons.Add("icon-cursor-move", '\ue023');
            Icons.Add("icon-crop", '\ue024');
            Icons.Add("icon-chemistry", '\ue026');
            Icons.Add("icon-speedometer", '\ue007');
            Icons.Add("icon-shield", '\ue00e');
            Icons.Add("icon-screen-tablet", '\ue00f');
            Icons.Add("icon-magic-wand", '\ue017');
            Icons.Add("icon-hourglass", '\ue018');
            Icons.Add("icon-graduation", '\ue019');
            Icons.Add("icon-ghost", '\ue01a');
            Icons.Add("icon-game-controller", '\ue01b');
            Icons.Add("icon-fire", '\ue01c');
            Icons.Add("icon-eyeglass", '\ue01d');
            Icons.Add("icon-envelope-open", '\ue01e');
            Icons.Add("icon-envelope-letter", '\ue01f');
            Icons.Add("icon-bell", '\ue027');
            Icons.Add("icon-badge", '\ue028');
            Icons.Add("icon-anchor", '\ue029');
            Icons.Add("icon-wallet", '\ue02a');
            Icons.Add("icon-vector", '\ue02b');
            Icons.Add("icon-speech", '\ue02c');
            Icons.Add("icon-puzzle", '\ue02d');
            Icons.Add("icon-printer", '\ue02e');
            Icons.Add("icon-present", '\ue02f');
            Icons.Add("icon-playlist", '\ue030');
            Icons.Add("icon-pin", '\ue031');
            Icons.Add("icon-picture", '\ue032');
            Icons.Add("icon-handbag", '\ue035');
            Icons.Add("icon-globe-alt", '\ue036');
            Icons.Add("icon-globe", '\ue037');
            Icons.Add("icon-folder-alt", '\ue039');
            Icons.Add("icon-folder", '\ue089');
            Icons.Add("icon-film", '\ue03a');
            Icons.Add("icon-feed", '\ue03b');
            Icons.Add("icon-drop", '\ue03e');
            Icons.Add("icon-drawer", '\ue03f');
            Icons.Add("icon-docs", '\ue040');
            Icons.Add("icon-doc", '\ue085');
            Icons.Add("icon-diamond", '\ue043');
            Icons.Add("icon-cup", '\ue044');
            Icons.Add("icon-calculator", '\ue049');
            Icons.Add("icon-bubbles", '\ue04a');
            Icons.Add("icon-briefcase", '\ue04b');
            Icons.Add("icon-book-open", '\ue04c');
            Icons.Add("icon-basket-loaded", '\ue04d');
            Icons.Add("icon-basket", '\ue04e');
            Icons.Add("icon-bag", '\ue04f');
            Icons.Add("icon-action-undo", '\ue050');
            Icons.Add("icon-action-redo", '\ue051');
            Icons.Add("icon-wrench", '\ue052');
            Icons.Add("icon-umbrella", '\ue053');
            Icons.Add("icon-trash", '\ue054');
            Icons.Add("icon-tag", '\ue055');
            Icons.Add("icon-support", '\ue056');
            Icons.Add("icon-frame", '\ue038');
            Icons.Add("icon-size-fullscreen", '\ue057');
            Icons.Add("icon-size-actual", '\ue058');
            Icons.Add("icon-shuffle", '\ue059');
            Icons.Add("icon-share-alt", '\ue05a');
            Icons.Add("icon-share", '\ue05b');
            Icons.Add("icon-rocket", '\ue05c');
            Icons.Add("icon-question", '\ue05d');
            Icons.Add("icon-pie-chart", '\ue05e');
            Icons.Add("icon-pencil", '\ue05f');
            Icons.Add("icon-note", '\ue060');
            Icons.Add("icon-loop", '\ue064');
            Icons.Add("icon-home", '\ue069');
            Icons.Add("icon-grid", '\ue06a');
            Icons.Add("icon-graph", '\ue06b');
            Icons.Add("icon-microphone", '\ue063');
            Icons.Add("icon-music-tone-alt", '\ue061');
            Icons.Add("icon-music-tone", '\ue062');
            Icons.Add("icon-earphones-alt", '\ue03c');
            Icons.Add("icon-earphones", '\ue03d');
            Icons.Add("icon-equalizer", '\ue06c');
            Icons.Add("icon-like", '\ue068');
            Icons.Add("icon-dislike", '\ue06d');
            Icons.Add("icon-control-start", '\ue06f');
            Icons.Add("icon-control-rewind", '\ue070');
            Icons.Add("icon-control-play", '\ue071');
            Icons.Add("icon-control-pause", '\ue072');
            Icons.Add("icon-control-forward", '\ue073');
            Icons.Add("icon-control-end", '\ue074');
            Icons.Add("icon-volume-1", '\ue09f');
            Icons.Add("icon-volume-2", '\ue0a0');
            Icons.Add("icon-volume-off", '\ue0a1');
            Icons.Add("icon-calendar", '\ue075');
            Icons.Add("icon-bulb", '\ue076');
            Icons.Add("icon-chart", '\ue077');
            Icons.Add("icon-ban", '\ue07c');
            Icons.Add("icon-bubble", '\ue07d');
            Icons.Add("icon-camrecorder", '\ue07e');
            Icons.Add("icon-camera", '\ue07f');
            Icons.Add("icon-cloud-download", '\ue083');
            Icons.Add("icon-cloud-upload", '\ue084');
            Icons.Add("icon-envelope", '\ue086');
            Icons.Add("icon-eye", '\ue087');
            Icons.Add("icon-flag", '\ue088');
            Icons.Add("icon-heart", '\ue08a');
            Icons.Add("icon-info", '\ue08b');
            Icons.Add("icon-key", '\ue08c');
            Icons.Add("icon-link", '\ue08d');
            Icons.Add("icon-lock", '\ue08e');
            Icons.Add("icon-lock-open", '\ue08f');
            Icons.Add("icon-magnifier", '\ue090');
            Icons.Add("icon-magnifier-add", '\ue091');
            Icons.Add("icon-magnifier-remove", '\ue092');
            Icons.Add("icon-paper-clip", '\ue093');
            Icons.Add("icon-paper-plane", '\ue094');
            Icons.Add("icon-power", '\ue097');
            Icons.Add("icon-refresh", '\ue098');
            Icons.Add("icon-reload", '\ue099');
            Icons.Add("icon-settings", '\ue09a');
            Icons.Add("icon-star", '\ue09b');
            Icons.Add("icon-symbol-female", '\ue09c');
            Icons.Add("icon-symbol-male", '\ue09d');
            Icons.Add("icon-target", '\ue09e');
            Icons.Add("icon-credit-card", '\ue025');
            Icons.Add("icon-paypal", '\ue608');
            Icons.Add("icon-social-tumblr", '\ue00a');
            Icons.Add("icon-social-twitter", '\ue009');
            Icons.Add("icon-social-facebook", '\ue00b');
            Icons.Add("icon-social-instagram", '\ue609');
            Icons.Add("icon-social-linkedin", '\ue60a');
            Icons.Add("icon-social-pinterest", '\ue60b');
            Icons.Add("icon-social-github", '\ue60c');
            Icons.Add("icon-social-google", '\ue60d');
            Icons.Add("icon-social-reddit", '\ue60e');
            Icons.Add("icon-social-skype", '\ue60f');
            Icons.Add("icon-social-dribbble", '\ue00d');
            Icons.Add("icon-social-behance", '\ue610');
            Icons.Add("icon-social-foursqare", '\ue611');
            Icons.Add("icon-social-soundcloud", '\ue612');
            Icons.Add("icon-social-spotify", '\ue613');
            Icons.Add("icon-social-stumbleupon", '\ue614');
            Icons.Add("icon-social-youtube", '\ue008');
            Icons.Add("icon-social-dropbox", '\ue00c');
            Icons.Add("icon-social-vkontakte", '\ue618');
            Icons.Add("icon-social-steam", '\ue620');
        }
    }
}